# Generates appendix_generated.tex: all latest-batch figures + curated tables.
import csv, math, os

RES = r"C:/Users/gilmar.souza/repos/linsync/mouse-epilepsy-daria-anderson-experiment/results"
RUN = {'column':'initial_column_2026-05-27_2029',
       'parkes':'initial_parkes_2026-05-27_2030',
       'tvb':'initial_tvb_2026-05-27_2030'}
SCHEMES = ['column','parkes','tvb']
MICE  = ['Anderson_1','Anderson_2','Arnold_2','Arnold_3','Arnold_4','Arnold_5']
CASE  = ['Anderson_1','Anderson_2']
SLAB  = {'column':'\\texttt{column}','parkes':'\\texttt{parkes}','tvb':'\\texttt{tvb}'}

def esc(s):
    s=str(s)
    return (s.replace('\\','\\textbackslash ').replace('_','\\_')
             .replace('%','\\%').replace('&','\\&').replace('#','\\#'))

def mlab(m): return esc(m)

def fnum(x, sig=4):
    try: v=float(x)
    except (TypeError,ValueError): return esc(x)
    if math.isnan(v): return '--'
    return f'{v:.{sig}g}'

def fp(x):  # p-value, LaTeX math sci-notation for small values
    try: v=float(x)
    except (TypeError,ValueError): return esc(x)
    if math.isnan(v): return '--'
    if v==1: return '1'
    if v==0: return r'$<\!10^{-15}$'
    if v<1e-3:
        mant,exp=f'{v:.1e}'.split('e')
        return rf'${mant}\!\times\!10^{{{int(exp)}}}$'
    return f'{v:.3g}'

def fz(x):
    try: v=float(x)
    except (TypeError,ValueError): return esc(x)
    if math.isnan(v): return '--'
    return f'{v:.2f}'

def readcsv(path):
    with open(path, newline='', encoding='utf-8-sig') as fh:
        return list(csv.DictReader(fh))

def csvpath(scheme, sub, name):
    return os.path.join(RES, RUN[scheme], sub, name)

out=[]
W=out.append

# ============================ FIGURES ============================
W(r'\section{Full result figures (latest batch)}')
W(r'\label{app:figures}')
W(r'''This appendix reproduces \emph{every} figure generated by the three configuration-driven
pipeline runs of the latest batch (\texttt{column}, \texttt{parkes}, \texttt{tvb}; run 2026-05-27)
over the six-mouse cohort. A representative subset appears in the main text; the complete set is
collected here for reference. Within each panel grid the two \textsc{Anderson} case mice precede the
four \textsc{Arnold} controls.''')
W('')

# ---- C.1 Dst per scheme ----
W(r'\subsection{Network-level \texorpdfstring{$\Dst$}{Dst} across the cohort}')
W(r'\begin{figure}[H]\centering')
for s in SCHEMES:
    W(r'\begin{subfigure}{0.32\textwidth}\centering')
    W(r'\includegraphics[width=\linewidth]{appendix/D_st_cohort_%s.png}' % s)
    W(r'\caption{%s}' % SLAB[s])
    W(r'\end{subfigure}\hfill')
W(r'\caption{Per-mouse network $\Dst=\mathrm{trace}(\Omega)/N$ for each normalisation scheme. Only '
  r'\texttt{column} separates the strains; under \texttt{parkes}/\texttt{tvb} the cohort ranges overlap.}')
W(r'\end{figure}')
W('')

# ---- C.2 stability centralities per mouse + overview ----
W(r'\subsection{Per-region stability centralities}')
for s in SCHEMES:
    W(r'\begin{figure}[H]\centering')
    for i,m in enumerate(MICE):
        W(r'\begin{subfigure}{0.32\textwidth}\centering')
        W(r'\includegraphics[width=\linewidth]{appendix/stabilityCentralities_%s_%s_figure.png}' % (m,s))
        W(r'\caption{\textsc{%s}}' % mlab(m))
        W(r'\end{subfigure}\hfill')
    W(r'\caption{Per-region susceptibility $\Dto$ and influence $\Dfrom$ for all six mice, %s scheme.}' % SLAB[s])
    W(r'\end{figure}')
    W(r'\begin{figure}[H]\centering')
    W(r'\includegraphics[width=0.8\textwidth]{appendix/stabilityCentralities_summary_overview_%s.png}' % s)
    W(r'\caption{Cohort overview of stability centralities, %s scheme.}' % SLAB[s])
    W(r'\end{figure}')
    W('')

# ---- C.3 centrality correlations ----
W(r'\subsection{Centrality correlations}')
for s in SCHEMES:
    W(r'\begin{figure}[H]\centering')
    W(r'\begin{subfigure}{0.48\textwidth}\centering')
    W(r'\includegraphics[width=\linewidth]{appendix/centrality_corr_mean_%s.png}' % s)
    W(r'\caption{Cohort mean}')
    W(r'\end{subfigure}\hfill')
    W(r'\begin{subfigure}{0.48\textwidth}\centering')
    W(r'\includegraphics[width=\linewidth]{appendix/centrality_corr_bars_%s.png}' % s)
    W(r'\caption{$\Dto$, $\Dfrom$ vs classical}')
    W(r'\end{subfigure}')
    W(r'\caption{Centrality correlation summary, %s scheme.}' % SLAB[s])
    W(r'\end{figure}')
    W(r'\begin{figure}[H]\centering')
    for m in MICE:
        W(r'\begin{subfigure}{0.32\textwidth}\centering')
        W(r'\includegraphics[width=\linewidth]{appendix/centrality_corr_%s_%s.png}' % (m,s))
        W(r'\caption{\textsc{%s}}' % mlab(m))
        W(r'\end{subfigure}\hfill')
    W(r'\caption{Per-mouse centrality correlation matrices, %s scheme.}' % SLAB[s])
    W(r'\end{figure}')
    W('')

# ---- C.4 Anderson vs Arnold ----
W(r'\subsection{Anderson vs Arnold per-region contrasts}')
metr=[('D_to_i','$\\Dto$'),('D_k_to','$\\Dfrom$'),('BC','BC')]
for s in SCHEMES:
    W(r'\begin{figure}[H]\centering')
    for m in CASE:
        for key,lab in metr:
            W(r'\begin{subfigure}{0.32\textwidth}\centering')
            W(r'\includegraphics[width=\linewidth]{appendix/compare_anderson_vs_arnold_%s_%s_%s.png}' % (m,s,key))
            W(r'\caption{\textsc{%s}, %s}' % (mlab(m),lab))
            W(r'\end{subfigure}\hfill')
    W(r'\caption{Each case mouse against the four-control band, %s scheme: susceptibility $\Dto$, '
      r'influence $\Dfrom$, and betweenness BC.}' % SLAB[s])
    W(r'\end{figure}')
    W('')

# ---- C.5 left-right asymmetry ----
W(r'\subsection{Left--right asymmetry}')
for s in SCHEMES:
    W(r'\begin{figure}[H]\centering')
    for m in CASE:
        W(r'\begin{subfigure}{0.46\textwidth}\centering')
        W(r'\includegraphics[width=\linewidth]{appendix/compare_LR_asymmetry_%s_%s.png}' % (m,s))
        W(r'\caption{\textsc{%s}}' % mlab(m))
        W(r'\end{subfigure}\hfill')
    W(r'\begin{subfigure}{0.46\textwidth}\centering')
    W(r'\includegraphics[width=\linewidth]{appendix/LR_asymmetry_groupTest_%s.png}' % s)
    W(r'\caption{Homotopic-pair group test}')
    W(r'\end{subfigure}\hfill')
    W(r'\begin{subfigure}{0.46\textwidth}\centering')
    W(r'\includegraphics[width=\linewidth]{appendix/LR_asymmetry_systematic_%s.png}' % s)
    W(r'\caption{Systematic side bias}')
    W(r'\end{subfigure}')
    W(r'\caption{Left--right asymmetry views, %s scheme.}' % SLAB[s])
    W(r'\end{figure}')
    W('')

# ---- C.6 column cross-scheme comparison figures ----
W(r'\subsection{Cohort comparison figures (\texttt{column})}')
W(r'These two summary figures also appear in the main text (Fig.~\ref{fig:outliers}, Fig.~\ref{fig:lr}).')
W(r'\begin{figure}[H]\centering')
W(r'\begin{subfigure}{0.49\textwidth}\centering')
W(r'\includegraphics[width=\linewidth]{appendix/region_susc_outliers.png}')
W(r'\caption{Region susceptibility outliers}')
W(r'\end{subfigure}\hfill')
W(r'\begin{subfigure}{0.49\textwidth}\centering')
W(r'\includegraphics[width=\linewidth]{appendix/laterality_influence_outliers.png}')
W(r'\caption{Laterality influence outliers}')
W(r'\end{subfigure}')
W(r'\caption{Cohort-level Bonferroni-significant outliers, \texttt{column} scheme.}')
W(r'\end{figure}')
W('')

# ============================ TABLES ============================
W(r'\section{Full result tables (latest batch)}')
W(r'\label{app:tables}')
W(r'''Numeric summaries underlying the figures above. Complete per-node CSVs for every run are written
to the run folders by the pipeline (see Appendix~\ref{app:repro}).''')
W('')

# ---- D.1 Dst + rhoC combined ----
W(r'\subsection{Network \texorpdfstring{$\Dst$}{Dst} and spectral radius \texorpdfstring{$\rhoC$}{rho(C)}}')
dst={s:{r['mouse']:r for r in readcsv(csvpath(s,'dst_cohort','D_st_cohort_%s.csv'%s))} for s in SCHEMES}
W(r'\begin{table}[H]\centering\small')
W(r'\caption{Per-mouse $\Dst$ and $\rhoC$ for the three schemes. Case mice (\textsc{Anderson}) above the rule.}')
W(r'\begin{tabular}{@{}l ccc ccc@{}}\toprule')
W(r'& \multicolumn{3}{c}{$\Dst$} & \multicolumn{3}{c}{$\rhoC$} \\')
W(r'\cmidrule(lr){2-4}\cmidrule(lr){5-7}')
W(r'Mouse & \texttt{column} & \texttt{parkes} & \texttt{tvb} & \texttt{column} & \texttt{parkes} & \texttt{tvb} \\\midrule')
for i,m in enumerate(MICE):
    if i==2: W(r'\midrule')
    row=[mlab(m)]
    for s in SCHEMES: row.append(fnum(dst[s][m]['D_st']))
    for s in SCHEMES: row.append(fnum(dst[s][m]['rho_C'],6))
    W(' & '.join(row)+r' \\')
W(r'\bottomrule\end{tabular}\end{table}')
W('')

# ---- D.2 top regions by susceptibility ----
W(r'\subsection{Top regions by stability susceptibility}')
for s in SCHEMES:
    rows=[r for r in readcsv(csvpath(s,'stability_centralities','stabilityCentralities_summary_topnodes_%s.csv'%s))
          if r.get('is_trivial','0') in ('0','0.0')]
    def keyf(r):
        try: return float(r['mean_rank_susc'])
        except: return 1e9
    rows=sorted(rows,key=keyf)[:15]
    has_x0 = s=='tvb'
    W(r'\begin{table}[H]\centering\small')
    W(r'\caption{Top 15 non-trivial regions by mean susceptibility rank, %s scheme (lower rank = more central).}' % SLAB[s])
    if has_x0:
        W(r'\begin{tabular}{@{}rlccc@{}}\toprule')
        W(r'\# & Region & mean rank $\Dto$ & mean rank $\Dfrom$ & mean rank $\xcrit$ \\\midrule')
    else:
        W(r'\begin{tabular}{@{}rlcc@{}}\toprule')
        W(r'\# & Region & mean rank $\Dto$ & mean rank $\Dfrom$ \\\midrule')
    for i,r in enumerate(rows,1):
        cells=[str(i),esc(r['region']),fnum(r['mean_rank_susc'],3),fnum(r['mean_rank_infl'],3)]
        if has_x0: cells.append(fnum(r['mean_rank_x0'],3))
        W(' & '.join(cells)+r' \\')
    W(r'\bottomrule\end{tabular}\end{table}')
W('')

# ---- D.3 Anderson vs Arnold outliers ----
W(r'\subsection{Anderson vs Arnold per-region outliers}')
for s in SCHEMES:
    W(r'\begin{table}[H]\centering\small')
    W(r'\caption{Flagged per-region contrasts ($|z|\ge2$) vs the control band, %s scheme. '
      r'$p_b$ = Bonferroni-corrected $p$; $^{\ast}$ marks significance at $\alpha=0.05$.}' % SLAB[s])
    W(r'\begin{tabular}{@{}llrrrrrr@{}}\toprule')
    W(r'Mouse & Region & $z_{\mathrm{susc}}$ & $p_b^{\mathrm{susc}}$ & $z_{\mathrm{infl}}$ & '
      r'$p_b^{\mathrm{infl}}$ & $z_{\mathrm{BC}}$ & $p_b^{\mathrm{BC}}$ \\\midrule')
    any_row=False
    for m in CASE:
        rows=readcsv(csvpath(s,'anderson_vs_arnold','compare_anderson_vs_arnold_%s_%s_outliers.csv'%(m,s)))
        for r in rows:
            any_row=True
            def pb(v):
                t=fp(v)
                try: return (t+r'\textsuperscript{$\ast$}') if float(v)<0.05 else t
                except: return t
            W(' & '.join([mlab(m),esc(r['Region']),fz(r['z_susc']),pb(r['p_bonf_susc']),
                          fz(r['z_infl']),pb(r['p_bonf_infl']),fz(r['z_BC']),pb(r['p_bonf_BC'])])+r' \\')
    if not any_row: W(r'\multicolumn{8}{c}{(no nodes flagged)} \\')
    W(r'\bottomrule\end{tabular}\end{table}')
W('')

# ---- D.4 systematic laterality (combined) ----
W(r'\subsection{Systematic laterality}')
W(r'\begin{table}[H]\centering\small')
W(r'\caption{Cohort-wide sign-rank test of the normalised laterality index $\mathrm{LI}_{\mathrm{norm}}$ '
  r'against zero, all schemes. Side = inferred dominant hemisphere (nominal labels).}')
W(r'\begin{tabular}{@{}lllrrrl@{}}\toprule')
W(r'Scheme & Cohort & Metric & mean LI & sd LI & sign-rank $p$ & Side \\\midrule')
for s in SCHEMES:
    rows=readcsv(csvpath(s,'lr_asymmetry','LR_asymmetry_systematic_%s.csv'%s))
    for r in rows:
        W(' & '.join([SLAB[s],esc(r['cohort']),esc(r['metric']),fnum(r['mean_LI'],3),
                      fnum(r['sd_LI'],3),fp(r['signrank_p']),esc(r['inferred_dominant_side'])])+r' \\')
    if s!='tvb': W(r'\midrule')
W(r'\bottomrule\end{tabular}\end{table}')
W('')

# ---- D.5 homotopic-pair group tests ----
W(r'\subsection{Homotopic-pair laterality tests}')
for s in SCHEMES:
    rows=readcsv(csvpath(s,'lr_asymmetry','LR_asymmetry_groupTest_%s.csv'%s))
    def kp(r):
        try: return float(r['p_bonf'])
        except: return 1e9
    rows=sorted(rows,key=kp)[:10]
    W(r'\begin{table}[H]\centering\small')
    W(r'\caption{Per-pair Welch $t$-test between strains, %s scheme: 10 smallest Bonferroni $p$. '
      r'$\checkmark$ marks $p_b<0.05$.}' % SLAB[s])
    W(r'\begin{tabular}{@{}llrrrrc@{}}\toprule')
    W(r'Region & Metric & $\mathrm{LI}_{\mathrm{And}}$ & $\mathrm{LI}_{\mathrm{Arn}}$ & $t$ & $p_b$ & sig. \\\midrule')
    for r in rows:
        sig = r'$\checkmark$' if r.get('bonf_significant') in ('1','1.0') else ''
        W(' & '.join([esc(r['Region']),esc(r['Metric']),fnum(r['LI_anderson_mean'],3),
                      fnum(r['LI_arnold_mean'],3),fz(r['t_stat']),fp(r['p_bonf']),sig])+r' \\')
    W(r'\bottomrule\end{tabular}\end{table}')
W('')

with open(r'C:/Users/gilmar.souza/repos/linsync/report/appendix_generated.tex','w',encoding='utf-8') as fh:
    fh.write('\n'.join(out)+'\n')
print('wrote appendix_generated.tex,', len(out), 'lines')
